
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Content"
    files:
      - name: "main"
        label: "Main Content"
        file: "content/site.json"
        fields:
          - { name: clubName, label: Club Name, widget: string, default: "Issaquah High School DECA" }
          - { name: tagline, label: Tagline, widget: string, default: "Emerging Leaders & Entrepreneurs" }
          - { name: schoolYear, label: School Year, widget: string, default: "2025–2026" }

          - { name: advisors, label: Advisors, widget: list, fields:
              [
                { name: name, label: Name, widget: string },
                { name: email, label: Email, widget: string, required: false },
                { name: room, label: Room, widget: string, required: false }
              ]
            }

          - { name: officers, label: Officers, widget: list, fields:
              [
                { name: name, label: Name, widget: string },
                { name: role, label: Role, widget: string },
                { name: email, label: Email, widget: string, required: false }
              ]
            }

          - { name: faq, label: FAQ, widget: list, fields:
              [
                { name: q, label: Question, widget: string },
                { name: a, label: Answer, widget: text }
              ]
            }

          - { name: social, label: Social Links, widget: list, fields:
              [
                { name: label, label: Label, widget: string },
                { name: href, label: URL, widget: string }
              ]
            }

          - { name: hero, label: Hero Buttons, widget: object, fields:
              [
                { name: ctaPrimary, label: Primary Button, widget: object, fields:
                    [
                      { name: label, label: Label, widget: string, default: "Join DECA" },
                      { name: href, label: Link, widget: string, default: "#" }
                    ]
                  },
                { name: ctaSecondary, label: Secondary Button, widget: object, fields:
                    [
                      { name: label, label: Label, widget: string, default: "Competition Guide" },
                      { name: href, label: Link, widget: string, default: "#calendar-sec" }
                    ]
                  }
              ]
            }
